import { Achievement, Character, MarketItem, Quest } from '../types/game';

// Fresh New User Default Character
export const NEW_USER_CHARACTER: Character = {
  id: 'new_user',
  name: 'Novice Hero',
  level: 1,
  xp: 0,
  xp_to_next_level: 100, // 100 * 1^1.5 = 100
  gold: 0,
  current_streak: 0,
  longest_streak: 0,
  strength: 1,
  intelligence: 1,
  wisdom: 1,
  agility: 1,
  discipline: 1,
  equipped_avatar: 'avatar_cyber_hero',
  equipped_frame: 'frame_neon_cyan',
  equipped_theme: 'theme_dark_cyberpunk',
  equipped_title: 'Novice Adventurer',
};

// Demo Account A (Returning Experienced Hero)
export const ACCOUNT_A_CHARACTER: Character = {
  id: 'user_account_a',
  name: 'Kaelen Vance',
  level: 5,
  xp: 750,
  xp_to_next_level: 1118, // 100 * 5^1.5 = 1118
  gold: 420,
  current_streak: 5,
  longest_streak: 8,
  last_quest_completed_at: new Date(Date.now() - 86400000).toISOString(),
  strength: 42,
  intelligence: 78,
  wisdom: 55,
  agility: 38,
  discipline: 64,
  equipped_avatar: 'avatar_cyber_hero',
  equipped_frame: 'frame_neon_cyan',
  equipped_theme: 'theme_dark_cyberpunk',
  equipped_title: 'Code Sorcerer',
};

export const ACCOUNT_A_QUESTS: Quest[] = [
  {
    id: 'quest_a_1',
    title: '⚔️ Master JavaScript Async & Event Loop',
    description: 'Solve 3 advanced asynchronous patterns and refactor promise chains.',
    category: 'Coding',
    difficulty: 'Hard',
    duration_minutes: 45,
    min_duration_seconds: 2700,
    completed: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'quest_a_2',
    title: '🏋️ High-Intensity Strength Session',
    description: '45-minute hypertrophy resistance training focusing on upper body power.',
    category: 'Fitness',
    difficulty: 'Medium',
    duration_minutes: 30,
    min_duration_seconds: 1800,
    completed: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'quest_a_3',
    title: '📚 Read 25 Pages of System Design',
    description: 'Study scalable distributed systems architecture and database sharding.',
    category: 'Reading',
    difficulty: 'Easy',
    duration_minutes: 30,
    min_duration_seconds: 1800,
    completed: false,
    created_at: new Date().toISOString(),
  },
];

// Demo Account B (Fresh Level 1 Hero)
export const ACCOUNT_B_CHARACTER: Character = {
  id: 'user_account_b',
  name: 'Nova Prime',
  level: 1,
  xp: 0,
  xp_to_next_level: 100,
  gold: 0,
  current_streak: 0,
  longest_streak: 0,
  strength: 1,
  intelligence: 1,
  wisdom: 1,
  agility: 1,
  discipline: 1,
  equipped_avatar: 'avatar_cyber_hero',
  equipped_frame: 'frame_neon_cyan',
  equipped_theme: 'theme_dark_cyberpunk',
  equipped_title: 'Novice Adventurer',
};

export const ACCOUNT_B_QUESTS: Quest[] = [];

export const INITIAL_CHARACTER: Character = ACCOUNT_A_CHARACTER;
export const INITIAL_QUESTS: Quest[] = ACCOUNT_A_QUESTS;

export const MARKET_ITEMS: MarketItem[] = [
  {
    id: 'avatar_cyber_hero',
    name: 'Cyber Knight Avatar',
    type: 'avatar',
    rarity: 'COMMON',
    cost: 0,
    description: 'The default futuristic cyberpunk knight avatar.',
    icon: 'Shield',
  },
  {
    id: 'avatar_shadow_ninja',
    name: 'Shadow Assassin',
    type: 'avatar',
    rarity: 'UNCOMMON',
    cost: 250,
    description: 'Stealthy operative trained in swift, silent productivity precision.',
    icon: 'UserCheck',
  },
  {
    id: 'avatar_arcane_mage',
    name: 'Arcane Spellcaster',
    type: 'avatar',
    rarity: 'RARE',
    cost: 500,
    description: 'Master of high-level cognitive spells and focus manipulation.',
    icon: 'Sparkles',
  },
  {
    id: 'avatar_mech_warrior',
    name: 'Paladin Mechanoid',
    type: 'avatar',
    rarity: 'EPIC',
    cost: 850,
    description: 'Heavy armored mech engineered for unstoppable momentum.',
    icon: 'Cpu',
  },
  {
    id: 'avatar_void_lord',
    name: 'Void Archon',
    type: 'avatar',
    rarity: 'LEGENDARY',
    cost: 1500,
    description: 'Mythic entity wielding cosmic energy and absolute life mastery.',
    icon: 'Crown',
  },
  {
    id: 'frame_neon_cyan',
    name: 'Neon Cyan Border',
    type: 'frame',
    rarity: 'COMMON',
    cost: 0,
    description: 'Glowing cyan glassmorphic aura ring.',
    icon: 'Square',
  },
  {
    id: 'frame_solar_gold',
    name: 'Golden Champion Frame',
    type: 'frame',
    rarity: 'RARE',
    cost: 400,
    description: 'Radiant golden metallic border for distinguished heroes.',
    icon: 'Award',
  },
  {
    id: 'frame_cyber_pink',
    name: 'Cyberpunk Pulse Frame',
    type: 'frame',
    rarity: 'EPIC',
    cost: 750,
    description: 'Animated neon magenta pulse ring with energy particle flare.',
    icon: 'Zap',
  },
  {
    id: 'frame_void_flame',
    name: 'Void Knight Flame Frame',
    type: 'frame',
    rarity: 'LEGENDARY',
    cost: 1200,
    description: 'Forged from dark matter energy and ethereal purple fire.',
    icon: 'Flame',
  },
  {
    id: 'title_novice',
    name: 'Novice Adventurer',
    type: 'title',
    rarity: 'COMMON',
    cost: 0,
    description: 'The starting title of every ambitious hero.',
    icon: 'Bookmark',
  },
  {
    id: 'title_code_sorcerer',
    name: 'Code Sorcerer',
    type: 'title',
    rarity: 'UNCOMMON',
    cost: 200,
    description: 'For those who weave digital spells and conquer bugs.',
    icon: 'Code',
  },
  {
    id: 'title_fitness_titan',
    name: 'Titan of Strength',
    type: 'title',
    rarity: 'RARE',
    cost: 450,
    description: 'Awarded to warriors of discipline and physical prowess.',
    icon: 'Dumbbell',
  },
  {
    id: 'title_scholar',
    name: 'Grandmaster Scholar',
    type: 'title',
    rarity: 'EPIC',
    cost: 700,
    description: 'Reserved for relentless seekers of wisdom and mastery.',
    icon: 'BookOpen',
  },
  {
    id: 'title_sovereign',
    name: 'Legendary Sovereign',
    type: 'title',
    rarity: 'LEGENDARY',
    cost: 2000,
    description: 'The supreme title bestowed upon elite conquerors of real life.',
    icon: 'Crown',
  },
  {
    id: 'theme_dark_cyberpunk',
    name: 'Obsidian Cyberpunk',
    type: 'theme',
    rarity: 'COMMON',
    cost: 0,
    description: 'Dark obsidian UI with glowing cyan and gold accents.',
    icon: 'Palette',
  },
  {
    id: 'theme_emerald_matrix',
    name: 'Emerald Matrix',
    type: 'theme',
    rarity: 'RARE',
    cost: 500,
    description: 'Matrix green terminal aesthetic with phosphorescent glow.',
    icon: 'Terminal',
  },
  {
    id: 'theme_void_purple',
    name: 'Deep Space Void',
    type: 'theme',
    rarity: 'EPIC',
    cost: 900,
    description: 'Deep violet space interface with neon pink energy streams.',
    icon: 'Moon',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_1',
    code: 'FIRST_QUEST',
    name: 'First Quest',
    description: 'Complete your first quest and take your initial step into the RPG realm.',
    icon: 'CheckCircle2',
    category: 'Milestone',
    rarity: 'COMMON',
    required_count: 1,
    current_count: 0,
    unlocked: false,
  },
  {
    id: 'ach_2',
    code: 'EARLY_RISE',
    name: 'Early Rise',
    description: 'Maintain a 3-day consecutive quest streak.',
    icon: 'Flame',
    category: 'Streak',
    rarity: 'UNCOMMON',
    required_count: 3,
    current_count: 0,
    unlocked: false,
  },
  {
    id: 'ach_3',
    code: 'WARRIOR',
    name: 'Iron Warrior',
    description: 'Complete 10 Fitness or Health quests.',
    icon: 'Swords',
    category: 'Combat',
    rarity: 'RARE',
    required_count: 10,
    current_count: 0,
    unlocked: false,
  },
  {
    id: 'ach_4',
    code: 'SCHOLAR',
    name: 'Arcane Scholar',
    description: 'Complete 10 Study or Coding quests.',
    icon: 'GraduationCap',
    category: 'Wisdom',
    rarity: 'RARE',
    required_count: 10,
    current_count: 0,
    unlocked: false,
  },
  {
    id: 'ach_5',
    code: 'STREAK_MASTER',
    name: 'Streak Master',
    description: 'Reach an impressive 14-day consecutive quest streak.',
    icon: 'Zap',
    category: 'Streak',
    rarity: 'EPIC',
    required_count: 14,
    current_count: 0,
    unlocked: false,
  },
  {
    id: 'ach_6',
    code: 'LEVEL_10',
    name: 'Ascendant Hero',
    description: 'Reach character Level 10.',
    icon: 'Trophy',
    category: 'Progression',
    rarity: 'EPIC',
    required_count: 10,
    current_count: 0,
    unlocked: false,
  },
  {
    id: 'ach_7',
    code: 'CENTURION',
    name: 'Centurion',
    description: 'Complete 100 real-life quests.',
    icon: 'ShieldAlert',
    category: 'Mastery',
    rarity: 'LEGENDARY',
    required_count: 100,
    current_count: 0,
    unlocked: false,
  },
];
